name: Reusable Workflow Demo

on:
  workflow_call:
    inputs:
      test-input:
        description: 'Test input parameter'
        required: false
        type: string
        default: 'default-value'

jobs:
  reusable-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: |
          echo "Running from reusable workflow"
          echo "Input received: ${{ inputs.test-input }}"
      
      - name: Print key environment variables
        run: |
          echo "=== KEY ENVIRONMENT VARIABLES ==="
          echo "GITHUB_WORKFLOW_REF: $GITHUB_WORKFLOW_REF"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "GITHUB_WORKFLOW: $GITHUB_WORKFLOW"
          echo "GITHUB_JOB: $GITHUB_JOB"
          echo "GITHUB_ACTION_PATH: $GITHUB_ACTION_PATH"
          echo "================================="
      
      - name: Print all environment variables
        run: |
          echo "=== ALL ENVIRONMENT VARIABLES ==="
          env | sort
          echo "================================="
      
      - name: Print github context (as JSON)
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "=== GITHUB CONTEXT ==="
          echo "$GITHUB_CONTEXT"
          echo "======================"
      
      - name: Check event payload for reusable workflow info
        run: |
          echo "=== CHECKING EVENT PAYLOAD ==="
          if [ -f "${GITHUB_EVENT_PATH}" ]; then
            echo "Event payload contents:"
            cat "${GITHUB_EVENT_PATH}"
          else
            echo "Event payload file not found"
          fi
          echo "=============================="
      
      - name: Detect if using reusable workflow (using context)
        run: |
          echo "=== REUSABLE WORKFLOW DETECTION (using github context) ==="
          echo "github.workflow_ref: ${{ github.workflow_ref }}"
          echo "github.workflow_sha: ${{ github.workflow_sha }}"
          echo "GITHUB_WORKFLOW_REF env: ${GITHUB_WORKFLOW_REF}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "Complete job name: ${{ github.job }}"
          echo "============================================================"
